### ISSUE TITLE
Search for subnodes in accordion admin isn't possible

### ISSUE THREAD

**Issue by alexbredo** [fabiocaccamo/django-treenode#11]
Search for subnodes in accordion admin isn't possible, because the parent nodes are collapsed and can not be opened. 

**Model**:
`class Element(TreeNodeModel):
    TYPES = Choices('Namespace', 'Class', 'Object')
    name = models.CharField(max_length=255, blank=False,
                            null=False, unique=True)
    model_type = models.CharField(
        choices=TYPES, default=TYPES.Object, max_length=100)
    treenode_display_field = 'name'`

**Admin**:
`@admin.register(models.Element)
class ElementAdmin(TreeNodeModelAdmin):  # admin.ModelAdmin
    treenode_accordion = True
    autocomplete_fields = ['tn_parent']
    list_display = ('id', 'model_type', )
    search_fields = ['name', 'tn_parent__name']
    exclude = ('tn_priority', )
    form = TreeNodeForm`

**No search**: 
![grafik](https://user-images.githubusercontent.com/8522272/54818539-c9271600-4c99-11e9-95a3-9463b9e543de.png)

**Search for child node**:
![grafik](https://user-images.githubusercontent.com/8522272/54818560-d9d78c00-4c99-11e9-8552-0f768d8967cf.png)

**Comment by fabiocaccamo** [comment]
@alexbredo this is a known issue, the reason is that the accordion is created dynamically using the flat `<tr>` elements of the changelist.

Filtering the results would broke the accordion structure, for example if you search for an object which has 2 parents excluded from search you will see a broken structure.

A possible solution could be to disable the accordion functionality when the there is a search of a filter applied. What do you think about it?

**Comment by alexbredo** [comment]
This is a good idea! Thank you very much for your support!
So the solution could look like (working example):

```
@admin.register(models.Element)
class ElementAdmin(TreeNodeModelAdmin):  # admin.ModelAdmin
    treenode_accordion = True 
    # [...]

    def get_search_results(self, request, queryset, search_term):
        if search_term:
            ElementAdmin.treenode_accordion = False
        else:
            ElementAdmin.treenode_accordion = True
        return super(ElementAdmin, self).get_search_results(request, queryset, search_term)
```

**Comment by alexbredo** [comment]
Probably this could be added to TreeNodeModelAdmin as temporary workaround

**Comment by fabiocaccamo** [comment]
@alexbredo I will add support to this and release a new version soon.

**Comment by alexbredo** [comment]
Top, you're the best 👍

**Comment by fabiocaccamo** [comment]
@alexbredo you can install `0.13.0` version.
`ModelAdmin` options are changed, `treenode_accordion` option has been replaced by `treenode_display_mode` since a new `'breadcrumbs'` display mode can be used:
```python
# treenode_display_mode = TreeNodeModelAdmin.TREENODE_DISPLAY_MODE_ACCORDION
# treenode_display_mode = TreeNodeModelAdmin.TREENODE_DISPLAY_MODE_BREADCRUMBS
treenode_display_mode = TreeNodeModelAdmin.TREENODE_DISPLAY_MODE_INDENTATION
```
When there is an active `list_filter` o any query string, the display mode will default to `TreeNodeModelAdmin.TREENODE_DISPLAY_MODE_BREADCRUMBS` to preserve data visualization integrity.
