### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by natebgurutech** [fabiocaccamo/django-treenode#53]
I scripted creating about 1000 items into my tree and it's a bit slow to load the admin list display and even more slow if I use a `raw_id_field` for the parent ID (the popup takes like 20 seconds to load).

Is there a way to enable pagination in the admin panel?  It's just dumping the full 1000 I generated on each load.

**Comment by natebgurutech** [comment]
I answered my own question.  I didn't find it in the documentation but I poked around the code a bit.

In this file:
https://github.com/fabiocaccamo/django-treenode/blob/master/treenode/admin.py

it says 

```python
list_per_page = 1000
```

I reviewed what commands I had done to generate my tree and it was exactly 1000 items.  If I had made 1001 I would have seen the pagination.

I was able to override this value in my model admin class and set it to whatever I pleased =)

Thanks for the great tool guys, it's awesome!

**Comment by fabiocaccamo** [comment]
@natebgurutech `list_per_page` is a django admin option (not an option of this package), that's why it is not documented here.

I'm personally using this library on a production project with a tree of ~500 nodes and 4 levels of depth and it runs quite well, could you install the [django-debug-toolbar](https://django-debug-toolbar.readthedocs.io/en/latest/) and check the cause of the slowdown please?

**Comment by fabiocaccamo** [comment]
@natebgurutech any update?

**Comment by fabiocaccamo** [comment]
@natebgurutech I close this due to inactivity, I will re-open it if needed.
